/*      [ ЦВЕТА ]      */
/*      [ COLORS ]      */
#define C_F_WHITE                   0xFFFFFFFF
#define C_WHITE                     "{FFFFFF}"
#define C_F_BLACK                   0x000000FF
#define C_BLACK                     "{000000}"
#define C_F_EMERALD                 0x00FFB2FF
#define C_EMERALD                   "{00FFB2}"
#define C_F_GRAY                    0x666666FF
#define C_GRAY                      "{666666}"
#define C_F_LIGHTGRAY               0x999999FF
#define C_LIGHTGRAY                 "{999999}"
#define C_F_RED                     0xFF2244FF
#define C_RED                       "{FF2244}"
#define C_F_YELLOW                  0xFFCC22FF
#define C_YELLOW                    "{FFCC22}"
#define C_F_GREEN                   0x33DD00FF
#define C_GREEN                     "{33DD00}"
#define C_F_PURPLE                  0x9D3EA6FF
#define C_PURPLE                    "{9D3EA6}"