/*      [ СКИНЫ ПЕРСОНАЖЕЙ ]      */
/*      [ CHARACTER SKINS ]      */
new const Skins_Male[9][4] = {
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28},
    {18,21,22,28}
};

new const Skins_Female[9][2] = {
    {13,69},
    {13,69},
    {13,69},
    {13,69},
    {13,69},
    {13,69},
    {13,69},
    {13,69},
    {13,69}
};

/*      [ ПОЗИЦИИ ПОЯВЛЕНИЯ (ПРИ СПАВНЕ / СПАВН НЕ НАЙДЕН) ]      */
/*      [ SPAWN POSITIONS (AT SPAWN / SPAWN NOT FOUND) ]      */
new const Float:Positions_Spawn[MAX_POSITIONS_SPAWN][4] = { // X, Y, Z, Rotation
    {0.0, 0.0, 3.0, 0.0} // Default
};