/*      [ ИГРОК ]      */
/*      [ PLAYER ]      */
#define PLAYER_NOT_FOUND            "Игрок не в сети."
#define PLAYER_NOT_VALID            "Нельзя совершить данное действие над выбранным игроком."
#define PLAYER_NOT_ME               "Нельзя совершить данное действие на себе."

/*      [ КОМАНДЫ ]      */
/*      [ COMMANDS ]      */
#define COMMAND_INVALID             "Неверный синтаксис. Используйте: /%s"