/*      [ ИГРОК ]      */
/*      [ PLAYER ]      */
#define PLAYER_NOT_FOUND            "Игрок не в сети."
#define PLAYER_NOT_VALID            "Нельзя совершить данное действие над выбранным игроком."
#define PLAYER_NOT_ME               "Нельзя совершить данное действие на себе."
#define PLAYER_IN_VEHICLE           "Игрок находится в транспорте."
#define PLAYER_MISSING_ADMIN_LEVEL  "У Вас недостаточно прав для выполнения данной команды."

/*      [ КОМАНДЫ ]      */
/*      [ COMMANDS ]      */
#define COMMAND_INVALID             "Неверный синтаксис. Используйте: /%s"
#define COMMAND_NOT_FOUND           "Команда введена неверно или не найдена."