#define MAX_INITIAL_WORKS               (2) // Максимальное количество начальных работ | Maximum number of initial works

/*      [ ГРУЗЧИК ]      */
/*      [ LOADER ]      */
#define WORK_LOADER_ID                  (0) // Ид работы | Work ID

#define WORK_LOADER_NPC_INVITE_SKIN_ID  (16) // Ид скина для бота | Skin ID for the bot
#define WORK_LOADER_MALE_SKIN_ID        (27) // Ид мужского скина | Male Skin ID
#define WORK_LOADER_FEMALE_SKIN_ID      (191) // Ид женского скина | Female Skin ID

#define WORK_LOADER_PRICE_PER_BOX       (15) // Цена за один ящик | Price per box

#define WORK_LOADER_PICKUP_POINT        (2) // Максимальное количество точек взятия груза | Maximum number of pick-up points
#define WORK_LOADER_PUT_POINT           (2) // Максимальное количество точек сдачи груза | Maximum number of delivery points