#define MAX_INITIAL_WORKS               (3) // Максимальное количество начальных работ | Maximum number of initial works

/*      [ ГРУЗЧИК (ЛВ) ]      */
/*      [ LOADER (LV) ]      */
#define WORK_LOADER_LV_ID                  (0) // Ид работы | Work ID

#define WORK_LOADER_LV_NPC_INVITE_SKIN_ID  (16) // Ид скина для бота | Skin ID for the bot
#define WORK_LOADER_LV_MALE_SKIN_ID        (27) // Ид мужского скина | Male Skin ID
#define WORK_LOADER_LV_FEMALE_SKIN_ID      (191) // Ид женского скина | Female Skin ID

#define WORK_LOADER_LV_PRICE_PER_BOX       (15) // Цена за один ящик | Price per box

#define WORK_LOADER_LV_PICKUP_POINT        (2) // Максимальное количество точек взятия груза | Maximum number of pick-up points
#define WORK_LOADER_LV_PUT_POINT           (2) // Максимальное количество точек сдачи груза | Maximum number of delivery points

/*      [ ФЕРМЕР (ЛВ) ]      */
/*      [ FARMER (LV) ]      */
#define WORK_FARMER_LV_ID                  (1) // Ид работы | Work ID

#define WORK_FARMER_LV_NPC_INVITE_SKIN_ID  (34) // Ид скина для бота | Skin ID for the bot
#define WORK_FARMER_LV_MALE_SKIN_ID        (133) // Ид мужского скина | Male Skin ID
#define WORK_FARMER_LV_FEMALE_SKIN_ID      (56) // Ид женского скина | Female Skin ID

#define WORK_FARMER_LV_PRICE_PER_HAY       (20) // Цена за один сноп сена | Price for one sheaf of hay

#define WORK_FARMER_LV_PICKUP_POINT        (4) // Максимальное количество точек взятия сена | Maximum number of hay collection points
#define WORK_FARMER_LV_PUT_POINT           (1) // Максимальное количество точек сдачи сена | Maximum number of hay delivery points

/*      [ ДАЙВЕР (ЛВ) ]      */
/*      [ DIVER (LV) ]      */
#define WORK_DIVER_LV_ID                    (2) // Ид работы | Work ID

#define WORK_DIVER_LV_NPC_INVITE_SKIN_ID    (32) // Ид скина для бота | Skin ID for the bot
#define WORK_DIVER_LV_MALE_SKIN_ID          (97) // Ид мужского скина | Male Skin ID
#define WORK_DIVER_LV_FEMALE_SKIN_ID        (251) // Ид женского скина | Female Skin ID

#define WORK_DIVER_LV_PRICE_PER_MARK        (5) // Цена за одну метку | Price per label

#define WORK_DIVER_LV_TAKE_BALLOON_POINT    (1) // Максимальное количество точек взятия баллона | Maximum number of balloon collection points
#define WORK_DIVER_LV_MARK_POINT            (4) // Максимальное количество точек | Maximum number of points